// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdaNpKhHpbscQVzRNn5Ks4U31SzKKLhFM',
    appId: '1:520134015169:web:243674a9a9f1df5de83c40',
    messagingSenderId: '520134015169',
    projectId: 'mealgenius-bc50f',
    authDomain: 'mealgenius-bc50f.firebaseapp.com',
    storageBucket: 'mealgenius-bc50f.appspot.com',
    measurementId: 'G-D8D3R6HNR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB18PbtEs8AfyA6Zk4CEC81LyRi05LBA1I',
    appId: '1:520134015169:android:0fda8c9f4a0a5de9e83c40',
    messagingSenderId: '520134015169',
    projectId: 'mealgenius-bc50f',
    storageBucket: 'mealgenius-bc50f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6ClgM-d5c86xdhAF_A7qrkibAXw1rrHk',
    appId: '1:520134015169:ios:46c5a3532cfc2b87e83c40',
    messagingSenderId: '520134015169',
    projectId: 'mealgenius-bc50f',
    storageBucket: 'mealgenius-bc50f.appspot.com',
    androidClientId: '520134015169-m22k9r4hfgidf1difpfjuiohbq5ajsdj.apps.googleusercontent.com',
    iosClientId: '520134015169-5tl19bd2rrf51c7hl32tgnb3f80skajl.apps.googleusercontent.com',
    iosBundleId: 'com.example.mealgenius',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6ClgM-d5c86xdhAF_A7qrkibAXw1rrHk',
    appId: '1:520134015169:ios:fd0d6197e3eb0c91e83c40',
    messagingSenderId: '520134015169',
    projectId: 'mealgenius-bc50f',
    storageBucket: 'mealgenius-bc50f.appspot.com',
    androidClientId: '520134015169-m22k9r4hfgidf1difpfjuiohbq5ajsdj.apps.googleusercontent.com',
    iosClientId: '520134015169-e0ktq1idtcdov8e6kucakfcv7orqnmp9.apps.googleusercontent.com',
    iosBundleId: 'com.example.mealgenius.RunnerTests',
  );
}
